# Generated by rust2rpm 27
%bcond check 1

Name:           trustee
Version:        0.15.0
Release:        %autorelease
Summary:        Tools and components for attesting confidential guests and providing secrets

License:        Apache-2.0

URL:            https://github.com/confidential-containers/trustee
Source0:        %{url}/archive/v%{version}.tar.gz

BuildRequires:  rust-packaging
BuildRequires:  cargo-rpm-macros >= 24

ExclusiveArch:  x86_64

%description
Tools and components for attesting confidential guests and providing secrets to them. Collectively, these components are known as Trustee. Trustee typically operates on behalf of the guest owner and interacts remotely with guest components, providing the necessary services for Attestation and Secret Delivery.

%package kbs
Summary:        Key Broker Service for Confidential Computing
Requires:       openssl

%description kbs
The KBS is a server that facilitates remote attestation and secret delivery.
Its role is similar to that of the Relying Party in the RATS model. The KBS
is part of the Trustee project which provides tools and components for
attesting confidential guests and providing secrets to them.

%prep
%autosetup -n %{name}-%{version}/kbs -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -n

%build
export OPENSSL_NO_VENDOR=1
%cargo_build -n
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files kbs
%license ../LICENSE LICENSE.dependencies
%doc README.md quickstart.md
%{_bindir}/kbs

%changelog
%autochangelog

